### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by starquake** [osuka/js-multiplatform-game03#1]
This repo is great! You exactly summed up things that annoy me too. What is the license of your code? Can I use this in a commercial game? Might I suggest a MIT license?

**Comment by osuka** [comment]
Hi yes you can use it. Glad you find it useful. Ideally you'd fork it and contribute back, but there's no obligation. I'm travelling and can't update it but will upload the standard MIT license file when I have time. Take this comment as license in the meantime. To make it clear: this code is released with MIT license.

**Comment by starquake** [comment]
That's great! And I will probably contribute back.
